---
title: "About Me"
---

<!-- ============================================================
     EDUCATION
     ============================================================ -->

## Education

**[PhD in Health Behavior and Health Equity]** — [University of Michigan], [Ongoing]  
*Relevant coursework: , Health communication, Epidemiology, Biostatistics, Global Health*

**[Masters in Public Health]** — [Brown University], [2023]  
*Relevant coursework: Epidemiology, Biostatistics, Global Health*

**[Bachelor of science Public Health]** — [Moi University], [2018]  
*Relevant coursework: Epidemiology, Biostatistics, Global Health*


<!-- ============================================================
     EXPERIENCE
     ============================================================ -->

## Experience

**[Graduate Student Research Assistant]** | [University of Michigan] | [January 2026 – May 2026]  
- Data analysis
- Preparing monthly progress reports
- Manuscript preparation

**[Graduate Student Instructor]** | [University of Michigan] | [September 2025 – December 2025]  
- Preparing class materials
- Holding office hours  
- Grading assignments and exams


## Projects

**[A scoping review of the needs of internally displaced persons who are at heightened risk of HIV in Ukraine]**  
Over the summer, I conducted a scoping review on the ongoing needs of internally displaced persons due to the ongoing war in Ukraine. The findings indicated that there are various unmet needs for our population of interest, including shelter, food, mental health, and social support.

## Honors & Awards
- Rackham International Students Fellowship/Chia-Lun Lo Fellowship- University of Michigan, 2025
- CEW+ Riecker Graduate Student Research Fund - CEW+, 2025
- University of Michigan Office of Global Public Health Travel Award- University of Michigan, 2025


## Interests / Hobbies
- Out of school I enjoy spending quality time with my family and friends. The beach is my favorite place to be. 